### ISSUE TITLE
fecDecode 出现错误 java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by testwen00** [l42111996/java-Kcp#11]
if (left > 0) {
                        shard.writeBytes(zeros, left);
                        zeros.resetReaderIndex();
 }

java.lang.IndexOutOfBoundsException: writerIndex(283) + minWritableBytes(1111) exceeds maxCapacity(283): PooledSlicedByteBuf(ridx: 0, widx: 283, cap: 283/283, unwrapped: PooledUnsafeDirectByteBuf(ridx: 289, widx: 289, cap: 289))
	at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:296)
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:282)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1105)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1098)

**Comment by l42111996** [comment]
你的参数是什么样子的？
这种情况有没有什么简单的方法重现？

**Comment by testwen00** [comment]
server：
ChannelConfig channelConfig = new ChannelConfig();
        channelConfig.nodelay(true, 30, 2, true);
        channelConfig.setSndwnd(1024);
        channelConfig.setRcvwnd(1024);
        channelConfig.setMtu(1400);
        channelConfig.setFecDataShardCount(10);
        channelConfig.setFecParityShardCount(3);
        channelConfig.setAckNoDelay(true);
        channelConfig.setTimeoutMillis(5000);
        channelConfig.setUseConvChannel(true);
        channelConfig.setCrc32Check(false);

client:
ChannelConfig channelConfig = new ChannelConfig();
        channelConfig.nodelay(true, 30, 2, true);
        channelConfig.setSndwnd(1024);
        channelConfig.setRcvwnd(1024);
        channelConfig.setMtu(1400);
        channelConfig.setFecDataShardCount(10);
        channelConfig.setFecParityShardCount(3);
        channelConfig.setAckNoDelay(true);
        channelConfig.setConv(UUID.randomUUID());
        channelConfig.setUseConvChannel(true);
        channelConfig.setCrc32Check(false);

测试发送的视频数据，数据包比较大，例如：一个包有230119个字节。

目前看代码逻辑还需要时间，所以我还无法给出重现的测试用例。

**Comment by testwen00** [comment]
是我这边修改byebuf造成，ServerChannelHandler 修改为继承SimpleChannelInboundHandler，read里采用了copy bytebuf，所以造成此问题
