### ISSUE TITLE
FecEncode 多线程安全问题

### ISSUE THREAD

**Issue by testwen00** [l42111996/java-Kcp#13]
能否改成线程安全的

变量在多线程下容易被改变，无法单独抽出。
 //count the number of datashards collected
    private int shardCount;

造成java.lang.ArrayIndexOutOfBoundsException: 14 错误

**Comment by l42111996** [comment]
有哪种需求会出现多线程并发调用同一个FecEncode 实例？
最好的方式是单连接串行，多连接并行，单连接下面如果要用到多核可以将串行的任务分成多个子任务，每个子任务并行，整个父任务是串行，这样子就无锁了，降低cpu自旋上面浪费的时间片和线程切换开销
如果并发调用fecEncode的方法只把shardCount改成线程安全是解决不了问题的，得把encode,release方法都加锁。

**Comment by testwen00** [comment]
我在尝试kcp和fec功能分开，目前看到代码中有几处会调用flash，需要readProcessing，writeProcessing来控制？，希望能功能分开，例如fec加入到rtp协议中。

**Comment by l42111996** [comment]
因为fec恢复包会导致kcp层面计算rtt值不准确，所以kcp层面需要知道哪个包是fec恢复。所以就有点耦合。

#https://github.com/xtaci/kcp-go/issues/63

readProcessing，writeProcessing是为了减少ReadTask和WriteTask对象的数量，如果是基于netty框架的你可以把fec单独放到一个eventloop里面去
