### ISSUE TITLE
1.5版本的maven包和代码示例不同

### ISSUE THREAD

**Issue by qlql489** [l42111996/java-Kcp#19]
代码示例中有FecAdapt
 channelConfig.setFecAdapt(new FecAdapt(3,1));  
maven包中没有
![image-20210427115018866](http://image.nianlun.tech/2021/04/27/756fc0cba99e09804ac7cfea4b7f04f6.png)

**Comment by l42111996** [comment]
没有很重要的bug和性能优化就没有发版本到maven仓库，可以直接用maven仓库的版本比较稳定

**Comment by l42111996** [comment]
maven仓库已经升到最新代码版本
