### ISSUE TITLE
一点建议与问题

### ISSUE THREAD

**Issue by dslchd** [l42111996/java-Kcp#2]
1.如果是基于jdk8，可以将AtomicInteger 或 AtomicLong 换成LongAdder, 这将会在高并发下有更好的性能。
2.目前看了点源码发现TimerThreadFacotry拼写错了IDEA都检测出来了,可以改一下。

请问在LockStepSynchronizationServer/client中约定的KCP 相关参数配置是最佳实践不？
是否在生产项目中也是如此设置呢？
thanks!

**Comment by l42111996** [comment]
谢谢你的建议，有些地方已经修改
LockStepSynchronizationServer/client中约定的KCP 相关参数配置不是最佳实践
应该按用户分级和地区分区去调整参数会更好点
比如 重度付费的用户可以让参数加上fec，浪费更多流量带来更低延迟
或者 如果跨洲际丢包率高的场景也可以加上fec参数   

可以参考 https://github.com/skywind3000/kcp/wiki/Flow-Control-for-Users

回头有时间会考虑动态优化fec参数和窗口大小

**Comment by dslchd** [comment]
非常感谢你及时的回复，我们也打算采用KCP 来做帧同步手游，由于之没有玩过这个，你开源的项目给了我们很多的参考。
