### ISSUE TITLE
断线重连问题

### ISSUE THREAD

**Issue by qlql489** [l42111996/java-Kcp#20]
测试java client端重启模拟断线重连的情况，使用Conv标识用户，断开到重启的时间没有超过timeout时间，client端重启后server业务层收不到数据，看服务端代码，重启后客户端发送的sn从0重新开始，但小于之前的rcvNxt所以直接跳过，请问这个如何解决，您提到的wifi切4g不会存在这个问题吗，代码如下：
![](http://image.nianlun.tech/2021/05/19/0a55c339ae25c32cf18567940f0a7aaa.png)

**Comment by l42111996** [comment]
timeout是指的没有收到消息timeout时间认为连接断开了，服务器和客户端都要设置timeout，这里rcvNxt >sn(0)出现是服务器没有设置timeout认为当前连接还是老的连接，所以拒绝收到新连接的包。

最佳实践应该是：业务层有个心跳包，客户端在没有发消息N秒后发送一个心跳包ping，服务器收到会立即返回一个心跳包pong，服务器和客户端设置timeout值为2N秒。

wifi切换4G跟上面的问题不是同一个问题，conv标识用户的意义在于只要conv值相同就认为是同一个用户，tcp是用 localIp+localPort+remoteIP+remotePort确定是同一个用户的，wifi切换4G后 localIP和localPort会变动导致tcp连接断开，而用conv确认为一个用户则这种情况下不会断开连接

**Comment by qlql489** [comment]
你说的我明白，我这里设置了30s的timeout，就是因为客户端重启的时间在30s内，所以server没有认为它断联才导致这个问题，比如实际客户端是手机app，用户杀进程在30s内再启动发送消息应该也会导致上面的问题，这只能减少timeout的时间吗

**Comment by l42111996** [comment]
现在是得等一段时间，有这个问题，还没想到好的办法，有什么好的建议可以提提

**Comment by l42111996** [comment]
> 你说的我明白，我这里设置了30s的timeout，就是因为客户端重启的时间在30s内，所以server没有认为它断联才导致这个问题，比如实际客户端是手机app，用户杀进程在30s内再启动发送消息应该也会导致上面的问题，这只能减少timeout的时间吗


如果应用关了再打开的话conv应该会变吧？什么情况下需要conv一致？

**Comment by qlql489** [comment]
我们的conv直接用的用户标识，应用杀进程重启用户标识不会变啊，不能这么用吗

**Comment by l42111996** [comment]
> 我们的conv直接用的用户标识，应用杀进程重启用户标识不会变啊，不能这么用吗

如果尝试换新的conv是否可以实现呢？  conv最开始设计是为了做连接标识的，并不是业务的用，唯一标识，关了再打开应用应该是一个新的连接才对。
