### ISSUE TITLE
新加的conv支持 在user创建时 存在bug

### ISSUE THREAD

**Issue by zhanghuaizheng** [l42111996/java-Kcp#24]
![image](https://user-images.githubusercontent.com/36873228/176165094-7224a29b-44fa-4ca4-a361-e26b9da7b94a.png)
应该增加相关conv值得判断拦截， 否则会造成多客户端都是conv值为0的情况，不能存储对应链接

修改后：
![image](https://user-images.githubusercontent.com/36873228/176165193-058d177f-699d-43d3-8e06-3870956ea42f.png)

**Comment by l42111996** [comment]
在什么情况下会出现很多客户端都是conv为0的情况？ 客户端发来的协议的conv都是0吗？
使用ServerConvChannelManager 会使用客户端发来的第一个包里面的conv作为一个链接的唯一标识，在客户端初始化之前需要设计一套conv计算方案确定每一个客户端唯一标识。

**Comment by zhanghuaizheng** [comment]
大概是我使用错误？ 当客户端设置conv以后，服务器端配置 useConvChannel 必须设置为true?

**Comment by l42111996** [comment]
useConvChannel的为true的时候使用conv作为一个链接的唯一标识，conv由客户端设置，在一些场景使用很好，比如手机从wifi切换为4g模式，连接不会断开
如果为false的话，conv字段就没有意义，跟tcp的设计思路一样根据端口+ip作为一个链接的唯一标识

**Comment by zhanghuaizheng** [comment]
所以这个就需要使用者明确知道 客户端设置conv值 服务端那个字段useConvChannel 必须设置为true， 对吧~

**Comment by l42111996** [comment]
是的
> 所以这个就需要使用者明确知道 客户端设置conv值 服务端那个字段useConvChannel 必须设置为true， 对吧~
