### ISSUE TITLE
请问这个可以和kcp-go互相通信吗

### ISSUE THREAD

**Issue by ProtossGenius** [l42111996/java-Kcp#3]
我想使用kcp-go作为服务器，java作为客户端，不过没有找到比较易懂的示例，请问可以告诉我哪个文件可以作为参考吗？多谢了。
希望能够有个类似于下面代码的简单示例，非常感谢。

```
package main

import (
	"fmt"
	"io"
	"net"
	"github.com/pkg/errors"
	"github.com/xtaci/kcp-go"
	"time"
)

func checkerr(err error) {
	if err != nil {
		panic(err)
	}
}

func Svr(laddr string) {
	lis, err := kcp.ListenWithOptions(laddr, nil, 10, 3)
	checkerr(err)
	for {
		conn, e := lis.AcceptKCP()
		checkerr(e)
		fmt.Println(conn.RemoteAddr())
		go func(conn net.Conn) {
			var buff = make([]byte, 1024, 1024)
			for {
				n, e := conn.Read(buff)
				if e != nil {
					if e == io.EOF {
						break
					}
					fmt.Println(errors.Wrap(e, "hello?"))
					break
				}
				fmt.Println("recv from client:", buff[:n])
			}
		}(conn)
	}
}

func main() {
	go Svr(":10000")
	go Svr(":10001")
	clt, err := kcp.DialWithOptions("localhost:10001", nil, 10, 3)
	checkerr(err)
	clt.Write([]byte("hello!!!!!11111111111111111111111111"))
	clt.Write([]byte("hello!!!!!2222222222222222222222222222222"))
	for {
		time.Sleep(1 * time.Second)
	}
}
```

**Comment by l42111996** [comment]
写的时候是兼容kcp-go来写的，但是我还没测试过，有些参数需要禁用比如加密这块java还未实现，等下我测试一下

**Comment by l42111996** [comment]
测了一下可以兼容，可以多些一点来回的消息测试因为fec那块的消息id计算方式需要测试一下。有问题可以在issues提

`public class KcpGoExampleClient implements KcpListener {

    public static void main(String[] args) {
        ChannelConfig channelConfig = new ChannelConfig();
        channelConfig.nodelay(true,40,2,true);
        channelConfig.setSndwnd(1024);
        channelConfig.setRcvwnd(1024);
        channelConfig.setMtu(1400);
        channelConfig.setFecDataShardCount(10);
        channelConfig.setFecParityShardCount(3);
        channelConfig.setAckNoDelay(false);
        //channelConfig.setTimeoutMillis(10000);
        channelConfig.setCrc32Check(false);

        KcpClient kcpClient = new KcpClient();
        kcpClient.init(Runtime.getRuntime().availableProcessors(),channelConfig);


        KcpGoExampleClient kcpGoExampleClient = new KcpGoExampleClient();
        Ukcp ukcp = kcpClient.connect(new InetSocketAddress("127.0.0.1", 10000), channelConfig, kcpGoExampleClient);
        String msg = "hello!!!!!11111111111111111111111111";
        byte[] bytes = msg.getBytes();
        ByteBuf byteBuf = ByteBufAllocator.DEFAULT.ioBuffer(bytes.length);
        byteBuf.writeBytes(bytes);
        ukcp.writeKcpMessage(byteBuf);

    }
    @Override
    public void onConnected(Ukcp ukcp) {

    }

    @Override
    public void handleReceive(ByteBuf byteBuf, Ukcp ukcp, int protocolType) {

    }

    @Override
    public void handleException(Throwable ex, Ukcp ukcp) {

    }

    @Override
    public void handleClose(Ukcp ukcp) {

    }
}
`

**Comment by ProtossGenius** [comment]
非常感谢，已经测试通过了。

**Comment by ProtossGenius** [comment]
还有一点小建议
```

    public Ukcp connect(InetSocketAddress remoteAddress, ChannelConfig channelConfig, KcpListener kcpListener) {
        ChannelFuture channelFuture = this.bootstrap.bind(new InetSocketAddress(0));
```
这里本地端口默认绑定了0，如果是做内网穿透的话或许需要指定本地端口，您可以看一下是否可以添加一个方法来允许用户绑定本地端口。

**Comment by l42111996** [comment]
在内网穿透的哪种情况下需要制定本地端口？  可以举个例子

**Comment by l42111996** [comment]
[已增加接口](https://github.com/l42111996/java-Kcp/commit/0113eaface4d4316ece0d863adafb4fa6e31ff70)

**Comment by ProtossGenius** [comment]
多谢大佬，只是感觉绑定端口代码会好写一点。
