### ISSUE TITLE
 反馈个问题（不知道算不算bug），一个客户端程序，如果建立两个KcpClient实例，去连接服务端。第2实例在服务端不会触发 onConnected事件

### ISSUE THREAD

**Issue by noear** [l42111996/java-Kcp#33]

**Comment by l42111996** [comment]
能否提供客户端和服务器端的参数。

**Comment by noear** [comment]
这个问题，我可能知道原因了。。。conv 有关：）。。。如果我设置不同的 conv ，就可以在一个客户端程序里，建立多个 KcpClient :)

//我是有单测涉及到这个，日常应该不会建多个实例

**Comment by noear** [comment]
即然你来了，帮忙看看代码。我是在实现一个网络应用协议：）

**Comment by noear** [comment]
https://github.com/noear/socket.d/blob/main/java/socketd-transport/socketd-transport-java-tcp/src/main/java/org/noear/socketd/transport/java_tcp/TcpBioClientConnector.java

这是客户端构建实例的代码，帮忙看看配置参数有没有什么可优化的；）

**Comment by noear** [comment]
https://github.com/noear/socket.d/blob/main/java/socketd-transport/socketd-transport-java-tcp/src/main/java/org/noear/socketd/transport/java_tcp/TcpBioServer.java

这是服务端的；）//我是直接在你的 demo 那儿 copy 过来的

**Comment by noear** [comment]
https://socketd.noear.org/article/protocol

//这是协议描述：）
