### ISSUE TITLE
1.6.1 什么时候发啊？另外 Conv 是什么意思，作什么用的？

### ISSUE THREAD

**Issue by noear** [l42111996/java-Kcp#34]
我测试，如果 server 重启；；；原客户端，发的消息就过不去了。。。有没有什么方案？

**Comment by l42111996** [comment]
1.61前两天发的，没有做什么功能上的更新，netty版本更新了一下。
conv可以用作客户端的唯一标识，不同的客户端连接使用不同的conv值作为唯一标识
server重启之后客户端发不出去，正常客户端应该显示断开连接，由于kcp没有挥手协议，使用的是心跳作为链接是否存活检测方案没办法立即检测断开连接，可以给客户端参数设置个心跳时间，时间到了认为连接断开了

**Comment by noear** [comment]
使用与不使用 Conv 做为客户端标准，会有什么区别？

**Comment by noear** [comment]
使用与不使用 Conv 做为客户端标准，会有什么区别？

**Comment by noear** [comment]
https://repo1.maven.org/maven2/com/github/l42111996/kcp-base/

查了下，1.6.1 仓库里还没有！是发到别处了？

**Comment by l42111996** [comment]
> https://repo1.maven.org/maven2/com/github/l42111996/kcp-base/
> 
> 查了下，1.6.1 仓库里还没有！是发到别处了？

我得问题没有传上去，现在传上去了等等就同步了

**Comment by noear** [comment]
还是没有！
