### ISSUE TITLE
KCP Disconnected And Reconnected Frequently

### ISSUE THREAD

**Issue by congcoi123** [l42111996/java-Kcp#37]
Hi,

Thank you for your contribution.
I am integrating KCP into my game server, however, it is struggling with automatically disconnecting and reconnecting.
There is no issue running it locally, but when I deployed the server to my VPS, the problem occurred. 
I've attached the log for that symptom.
<img width="1284" alt="Screenshot 2024-03-20 at 04 17 46" src="https://github.com/l42111996/java-Kcp/assets/4993410/6a7530c1-86b9-4180-a2f4-afbc0065601f">

Would you happen to have any ideas on how to troubleshoot it?

**Comment by congcoi123** [comment]
It seems there might be some issues occurred so the ukcp got closed. I will put some logs here and check. Let's see.
![image](https://github.com/l42111996/java-Kcp/assets/4993410/6eeb2ba6-0e43-423b-9e2a-a8ac4009e90a)

**Comment by congcoi123** [comment]
The issue comes from this FEC. I removed the library and am trying to retest it.
<img width="906" alt="Screenshot 2024-03-20 at 21 14 21" src="https://github.com/l42111996/java-Kcp/assets/4993410/daa79db1-6ec3-4b29-9990-82e5f11d090e">
<img width="1339" alt="Screenshot 2024-03-20 at 21 27 47" src="https://github.com/l42111996/java-Kcp/assets/4993410/a42523ab-92ca-4392-8e4a-075528e532d9">

**Comment by congcoi123** [comment]
@l42111996 I would like to raise a PR which is just for putting some reason logs when the connection gets disconnected. What do you think about it?

**Comment by l42111996** [comment]
Can you provide the parameter information codes at both ends? Which library is used on the client side? fec is a function unique to this version, not a function of the original version of kcp. If the libraries used are inconsistent, it may be a problem with this parameter. Try disabling fec.

**Comment by congcoi123** [comment]
Hi @l42111996,
Thank you for the response. Both client and server are using the same Java library. The configuration is the same except the client does not need to declare the timeout.
<img width="640" alt="Screenshot 2024-03-21 at 18 40 19" src="https://github.com/l42111996/java-Kcp/assets/4993410/bc8f983d-f781-467e-8412-2de9d42b9921">

I disabled the FEC configuration and it's being tested on my game. Let's see how it performs.

Regarding the integration of KCP into my game server, here is the PR:
https://github.com/congcoi123/tenio-core/pull/50/files

**Comment by l42111996** [comment]
I guess it is not a problem with fec. Whether the connection to this library is available is based on the heartbeat timeout. For messages not included in the library, you need to write a heartbeat mechanism in the business layer. If no message is received within the TimeoutMills time, the library will Think the network has been disconnected

**Comment by congcoi123** [comment]
If you check this screenshot, you may find the exceptional log.
https://github.com/l42111996/java-Kcp/issues/37#issuecomment-2010629245

Your framework is in testing on my Android game, let's see how it works.

**Comment by l42111996** [comment]
I'm on vacation. I'll take a look at this issue in a few days.

**Comment by congcoi123** [comment]
I appreciate your time.

**Comment by l42111996** [comment]
The problem has been fixed and the latest source code is used. The C language version used by fec by default. If the platform you are using does not compile the corresponding library, you can compile it yourself. I only tested successfully on the windows and  arm macos platform. The warehouse address is https://github.com/l42111996/reedsolomon_jni

**Comment by congcoi123** [comment]
@l42111996 Many thanks for your time 苗大哥 I will test it and update you.
