### ISSUE TITLE
支持Android端吗

### ISSUE THREAD

**Issue by wangpeng1** [l42111996/java-Kcp#4]

**Comment by l42111996** [comment]
我没试过，理论都是支持的，你可以试试如果有什么问题可以提上来我协助修改

**Comment by qktang** [comment]
Android集成的时候需要java8支持，需要依赖'com.lmax:disruptor:3.4.2' ，但是打包时会报"MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)"错误

**Comment by l42111996** [comment]
> Android集成的时候需要java8支持，需要依赖'com.lmax:disruptor:3.4.2' ，但是打包时会报"MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)"错误

线程池这块其实可以不用disruptor的，我抽象一下成配置
