### ISSUE TITLE
使用conv模式情况下，客户端连上服务器后，关闭客户端再登录，大概率会导致通讯失败。使用KcpReconnectExampleClient示例很容易出现。 

### ISSUE THREAD

**Issue by evallili** [l42111996/java-Kcp#40]
使用conv模式情况下，客户端连上服务器后，关闭客户端再登录，大概率会导致通讯失败。使用KcpReconnectExampleClient示例很容易出现。

**Comment by l42111996** [comment]
把超时时间弄短点，或者在业务层加挥手协议，kcp是通过心跳机制检测链接是否存活的，如果在心跳时间内客户端关闭再登录，需要等心跳超时过了以后同样的conv才能链接上

**Comment by evallili** [comment]
![image](https://github.com/user-attachments/assets/3a33f9cb-5b30-4122-aa1d-934898ab2f99)
是否可以在接收数据这里，如果remoteAddress改变了，就关闭旧通道，使用新的通道。

**Comment by l42111996** [comment]
> ![image](https://private-user-images.githubusercontent.com/12540222/353277377-3a33f9cb-5b30-4122-aa1d-934898ab2f99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMTk5OTAsIm5iZiI6MTcyMjMxOTY5MCwicGF0aCI6Ii8xMjU0MDIyMi8zNTMyNzczNzctM2EzM2Y5Y2ItNWIzMC00MTIyLWFhMWQtOTM0ODk4YWIyZjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA2MDgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0NjFhNWI3YzI0NGQyZWM2NTc0NzRmYWJlYTNkZDBhZGEzYWM3MzUyZjIzMjU2NDM1NzU2OTUzOWZjNTRkNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eqyUdySKHXfzCVDwmPN62uXCJCETS21ASyADa5h37H0) 是否可以在接收数据这里，如果remoteAddress改变了，就关闭旧通道，使用新的通道。

不可行，有一种需求是从4G切换到wifi 要保证网络链接不断开，这种情况下需要remoteAddress变了但是conv没变连接不断开。

**Comment by l42111996** [comment]
想了这个问题有一种解法：如果remoteAddress变了，conv没变，收到的包sn为0(消息的第一个包)，就用把老的链接关掉，用新的链接
