### ISSUE TITLE
关于获取网络丢包率的疑问

### ISSUE THREAD

**Issue by azui007** [l42111996/java-Kcp#41]
你好。我查看了Snmp内容，未发现疑似的数据。
请问是否可以获取传输时的丢包率。

**Comment by l42111996** [comment]
snmp里面有丢包率的信息，总共重发数据就是包丢了需要重发的数据，丢包率 = (重发的数据包数量 / 发送的数据包总数量) × 100%

**Comment by azui007** [comment]
感谢回答，issue关闭了哈
