### ISSUE TITLE
C#有DotNetty，要是有一个C#版的就好了

### ISSUE THREAD

**Issue by SetoKaiba** [l42111996/java-Kcp#5]
C#有DotNetty，要是有一个C#版的就好了

**Comment by l42111996** [comment]
我有写一个基于dotNetty的net core版本,还在测试中没有开源出来，你用在什么方面？

**Comment by SetoKaiba** [comment]
客户端和服务端都想试试看。Unity的Linux也有IL2CPP和headless了，所以客户端服务端都想试试。

**Comment by l42111996** [comment]
等会我把它开源出来 
https://github.com/l42111996/csharp-kcp

**Comment by SetoKaiba** [comment]
啊，谢谢呀，我去试试。
