### ISSUE TITLE
Android集成的问题

### ISSUE THREAD

**Issue by qktang** [l42111996/java-Kcp#8]
Android集成的时候需要java8支持，需要依赖'com.lmax:disruptor:3.4.2' ，但是打包时会报"MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)"错误

**Comment by l42111996** [comment]
刚刚把线程池抽出来了默认使用netty线程池，可以不依赖disruptor，试试1.3版本

**Comment by qktang** [comment]
感谢，可以使用了
