### ISSUE TITLE
多连接下，int conv是否够用？

### ISSUE THREAD

**Issue by testwen00** [l42111996/java-Kcp#9]
是否改成long
另集群多进程通讯下，id由客户端设置，容易重复，改成uuid可好？或者有更好的建议

**Comment by l42111996** [comment]
原版协议里面conv是一个int ，所以就是这样子的了，集群可以考虑使用ip+address作为唯一标识跟tcp的方式一样，useConvChannel 这个参数设置为false就行了，

**Comment by l42111996** [comment]
用conv作为连接唯一标识的意义在于4G切换wifi的时候网络不会断开，4G切换wifi后ip和端口会变动，tcp(ip+port为唯一标识)这种方式就会出现网络断开。
为了防止tcp在4G切换wifi后连接断开，也有优化方案
https://blog.codingnow.com/2014/02/connection_reuse.html

这几种方式你可以参考选择一下。

**Comment by testwen00** [comment]
嗯，我已改成uuid，是可行的
